# Dataset configuration for FinanceMath ingestion.
dataset:
  name: "yale-nlp/FinanceMath"
  split: "validation"
  cache_dir: "./.cache/hf"
  use_auth_token: null

paths:
  raw: "data/raw"
  processed: "data/processed"

ingest:
  output_filename: "finance_math_validation.jsonl"
  max_examples: null  # Optional limit for quick experiments.
  invalid_output_filename: "finance_math_invalid.jsonl"
