name: mlops-demo

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Lint
        run: |
          ruff check src tests
          black --check src tests

      - name: Tests
        env:
          PYTHONPATH: src
          SKIP_MODEL_LOAD: "1"
        run: python -m pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build inference image
        run: docker build -f docker/inference.Dockerfile -t finance-math-api .

  drift-report:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate drift report
        id: drift
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          if [ -f data/processed/finance_math_features.parquet ]; then
            python scripts/generate_drift_report.py \
              --model-uri runs:/5d230e940f6749b4af7ad9783d673be4/model \
              --output data/processed/evidently_report.html
            echo "generated=true" >> "$GITHUB_OUTPUT"
          else
            echo "Skipping drift report generation; data/processed/finance_math_features.parquet not found."
            echo "generated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload drift report
        if: steps.drift.outputs.generated == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: evidently-report
          path: data/processed/evidently_report.html
